name: Checks

on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/**/*.cpp'
      - 'include/**/*.hpp'
      - 'tests/**/*.cpp'
      - 'CMakeLists.txt'
      - '.github/workflows/tests.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: MarkusJx/googletest-installer@28c5d4102d9d57b46254be19a940bf038a9c850a

      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcxxopts-dev \
            nlohmann-json3-dev \
            libsqlite3-dev \
            libcurl4-openssl-dev

      - name: Configure project
        run: |
          cmake -S . -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DBUILD_TESTS=ON

      - name: Build project
        run: cmake --build build --parallel

      - name: Run unit tests
        run: ctest --test-dir build --output-on-failure --parallel $(nproc)

  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Clang-format
        uses: jidicula/clang-format-action@c14d7abd6da6ba0aeed48797a5784d9468cbb806
        with:
          clang-format-version: '21'
          check-path: '.'